### ISSUE TITLE
On first ansible run service check fails

### ISSUE THREAD

**Issue by Otann** [truckerpathteam/playbook-initd-service#1]
On fresh node when you run this playbook this piece fails:

```yaml
- name: Ensure daemon is started
  sudo: yes
  service: 
    name: "{{ service_name }}"
    state: started
```

Also this probably shows that service is not restarted, so if you have replaced jar for example, old service is still running.
